import type { AlertSubscription, Provider, Report } from "@/lib/types";

export const providers: Provider[] = [
  {
    id: "provider-1",
    name: "칼의부활 수원트럭",
    baseArea: "수원 장안구",
    truckLabel: "1t 이동형 작업 트럭",
    mobileService: true,
    serviceTags: ["식칼", "가위", "나이프", "식당용"],
    serviceAreas: ["장안구", "권선구", "팔달구"],
    priceHints: ["식칼 8,000원~", "가위 7,000원~"],
    intro:
      "시장 출점과 주거지 방문을 병행하는 형태. 초기 지도를 채우는 bootstrap provider입니다.",
  },
  {
    id: "provider-2",
    name: "신의칼 출장연마",
    baseArea: "수원 영통구",
    truckLabel: "승합차 이동형 장비",
    mobileService: true,
    serviceTags: ["세라믹", "일식 나이프", "가위"],
    serviceAreas: ["영통구", "팔달구", "용인"],
    priceHints: ["세라믹 18,000원~", "나이프 15,000원~"],
    intro:
      "특수 재질과 고급 나이프 작업에 특화. official registry로 전환될 후보입니다.",
  },
  {
    id: "provider-3",
    name: "대장장이 칼갈이",
    baseArea: "수원 권선구",
    truckLabel: "시장 순회형 트럭",
    mobileService: true,
    serviceTags: ["식칼", "가위", "정육점 칼"],
    serviceAreas: ["권선구", "팔달구", "성남", "화성"],
    priceHints: ["정육점 칼 별도 협의", "출장비 0원~10,000원"],
    intro:
      "시장과 상권 순회 일정이 많고, 성남 방향 확장 후보로도 보는 provider입니다.",
  },
];

export const reports: Report[] = [
  {
    id: "report-1",
    district: "장안구",
    neighborhood: "정자동",
    place: "정자시장 입구 앞",
    truckType: "칼갈이 트럭",
    providerId: "provider-1",
    providerHint: "칼의부활 수원트럭",
    reportedAt: "2026-03-20T09:10:00+09:00",
    reportedLabel: "18분 전",
    trustScore: 92,
    status: "active",
    hasPhoto: true,
    reporterAlias: "시장상인",
    note: "가위 포함 접수 중. 줄은 3팀 정도.",
    lat: 37.3032,
    lng: 126.9991,
    sourceType: "seed_report",
  },
  {
    id: "report-2",
    district: "팔달구",
    neighborhood: "행궁동",
    place: "행궁동 공영주차장 앞",
    truckType: "칼갈이 트럭",
    providerId: "provider-3",
    providerHint: "대장장이 칼갈이",
    reportedAt: "2026-03-20T10:05:00+09:00",
    reportedLabel: "방금 전",
    trustScore: 88,
    status: "active",
    hasPhoto: true,
    reporterAlias: "행궁동 주민",
    note: "시장 방향으로 이동 예정.",
    lat: 37.2825,
    lng: 127.0147,
    sourceType: "seed_report",
  },
  {
    id: "report-3",
    district: "영통구",
    neighborhood: "매탄동",
    place: "매탄공원 남측",
    truckType: "이동식 칼갈이 밴",
    providerId: "provider-2",
    providerHint: "신의칼 출장연마",
    reportedAt: "2026-03-20T08:30:00+09:00",
    reportedLabel: "58분 전",
    trustScore: 79,
    status: "active",
    hasPhoto: false,
    reporterAlias: "아파트 주민",
    note: "세라믹 문의가 많았음.",
    lat: 37.2663,
    lng: 127.0401,
    sourceType: "seed_report",
  },
  {
    id: "report-4",
    district: "권선구",
    neighborhood: "세류동",
    place: "세류2동 주민센터 인근",
    truckType: "주민센터 칼갈이 부스",
    providerHint: "주민센터 연계",
    reportedAt: "2026-03-19T15:20:00+09:00",
    reportedLabel: "어제",
    trustScore: 84,
    status: "active",
    hasPhoto: true,
    reporterAlias: "동네 제보",
    note: "우산 수리와 함께 운영하는 듯 보임.",
    lat: 37.2551,
    lng: 127.0135,
    sourceType: "community_report",
  },
];

export const alertSubscriptions: AlertSubscription[] = [
  {
    id: "alert-1",
    district: "팔달구",
    anchorNeighborhood: "행궁동",
    radiusMeters: 1000,
    channel: "웹 푸시",
    nickname: "행궁동 알림",
    note: "저녁 시간대 제보 우선",
    sourceType: "seed",
  },
  {
    id: "alert-2",
    district: "영통구",
    anchorNeighborhood: "매탄동",
    radiusMeters: 1500,
    channel: "카카오 알림톡",
    nickname: "매탄동 주방팀",
    note: "업장용 칼갈이 제보 선호",
    sourceType: "seed",
  },
];
